package com.polisafik.storage_of_occult_products.models.enums;

public enum Category {
    CRYSTALS, INCENSE, TAROT_CARDS, CANDLES,
    HERBS, ESSENTIAL_OILS, ALTAR_TOOLS, AMULETS_AND_TALISMANS,
    BOOK_OF_SHADOWSBOOKS, PENDULUMS, JEWELRY, RITUAL_KITS,
    DIVINATION_TOOLS, ASTROLOGY_CHARTS, SMUDGING_SUPPLIES, SHAMANIC_DRUMS,
    SPELL_INGREDIENTS
}
